### ISSUE TITLE
风险建议

### ISSUE THREAD

**Issue by CherryLover** [loo-y/GeminiChatUp#1]
你好，这个项目挺好的，不过部署到 Vercel 上，是不是可以考虑加一个密码验证的页面，验证不通过，不进入 Chat 页面，因为可能存在被滥用的问题，另外 Gemini 也有用量限制的。

或者在网页上提供一个输入 Key 的入口，让使用者自行输入 Key，然后保存到本地缓存中。

**Comment by loo-y** [comment]
嗯，这个是后期考虑要加的功能，会先增加让用户自己提供API key的功能。
感谢提建议。

**Comment by hqzh** [comment]
vercel 500的情况大于正常的时候
![image](https://github.com/loo-y/GeminiChatUp/assets/26128706/66ac96a6-7999-497c-8a32-d86e70ff8701)

**Comment by hqzh** [comment]
![image](https://github.com/loo-y/GeminiChatUp/assets/26128706/bfaa9842-52bf-4478-b937-790aeb2167c3)
另外为啥我部署的没有附件上传按钮

**Comment by loo-y** [comment]
> ![image](https://private-user-images.githubusercontent.com/26128706/297943613-bfaa9842-52bf-4478-b937-790aeb2167c3.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDU2MzQ3ODIsIm5iZiI6MTcwNTYzNDQ4MiwicGF0aCI6Ii8yNjEyODcwNi8yOTc5NDM2MTMtYmZhYTk4NDItNTJiZi00NDc4LWI5MzctNzkwYWViMjE2N2MzLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMTklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTE5VDAzMjEyMlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWE4MjcyMzA3NjExNTc0YjVlZGU2MzVkMWY4NTRlNTUxOGE4MmQ1OTY2OTU2YTM4YmYxOWQ5MGEyMTIxZjBjNGEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.G9tqWnuEWNgdX4BjIpU5ytxZp47G1TIt6CBovR3Xe1o) 另外为啥我部署的没有附件上传按钮


你点下create按钮，选择 Vision Content

这里实际是分了2种模式。一种是chat，chat只支持 Gemini Pro
另一种是 Prompt Content，这个是支持 Gemini Pro Vision的，也就是图片上传。但这个 model 在官方并不支持对话Chat，我加了一些 Prompt把 Vision做成对话场景的

**Comment by hqzh** [comment]
![image](https://github.com/loo-y/GeminiChatUp/assets/26128706/e8f69815-4d1c-49b8-87e5-49aa84a6becd)

**Comment by loo-y** [comment]
> ![image](https://private-user-images.githubusercontent.com/26128706/297954537-e8f69815-4d1c-49b8-87e5-49aa84a6becd.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDU2MzkyNzIsIm5iZiI6MTcwNTYzODk3MiwicGF0aCI6Ii8yNjEyODcwNi8yOTc5NTQ1MzctZThmNjk4MTUtNGQxYy00OWI4LTg3ZTUtNDlhYTg0YTZiZWNkLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMTklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTE5VDA0MzYxMlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWI2Yjg1NzVjYjdkOTQ0ZmZhMTJkODk0MDE2MzM3M2RiNjNkMjM4NzI5ZmYwZDFhMDhlYjE5NGEyNTIzNWJiNjcmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0._-roznzcPHMa7vXmqtOV1s1BFh0hxSxMrwfOPpIwILU)


vercel 对于免费账号的接口请求限制是 10秒，但 Gemini Pro Vision 会比较慢，可以多试几次，或者换张图重新来。我目前不清楚改成流式是否可以改进这个现象。

**Comment by loo-y** [comment]
> 流式应该是可以处理这个问题。

好，我近期改下

**Comment by liujiaqi222** [comment]
![image](https://github.com/loo-y/GeminiChatUp/assets/51473151/ff266645-d5eb-4938-a37a-0060fa254e3b)

**Comment by loo-y** [comment]
> 你好，这个项目挺好的，不过部署到 Vercel 上，是不是可以考虑加一个密码验证的页面，验证不通过，不进入 Chat 页面，因为可能存在被滥用的问题，另外 Gemini 也有用量限制的。
> 
> 或者在网页上提供一个输入 Key 的入口，让使用者自行输入 Key，然后保存到本地缓存中。


已增加 用户凭证 / 添加 Gemini Pro API Key 功能。

**Comment by loo-y** [comment]
> 流式应该是可以处理这个问题。

流式我尝试过了，也受到10秒的限制，在10秒之后，即使 sse 的链接没有断，但仍旧不会继续返回信息。

不过我现在已经修改成 Edge runtime了，vercel 对于 Edge runtime 的超时是30秒，应该可以解决大部分断连场景。
