### ISSUE TITLE
如何获取api key？

### ISSUE THREAD

**Issue by liujiaqi222** [loo-y/GeminiChatUp#2]
现在只要打开这个网站[https://makersuite.google.com/app/apikey](https://makersuite.google.com/app/apikey)，就会重定向到[https://makersuite.google.com/app/apikey](https://ai.google.dev/available_regions?hl=zh-cn)，请问是否有解决方案？

**Comment by loo-y** [comment]
咦，那先访问 https://makersuite.google.com/ 试试呢？
我不清楚 google 现在是否还限制只能美国 IP 申请 Gemini Pro API

**Comment by liujiaqi222** [comment]
还是不行，估计不仅仅是限制IP，还因为我的谷歌账号绑定的号码是+86的

**Comment by loo-y** [comment]
我也是86手机哎

**Comment by liujiaqi222** [comment]
可能还是网络原因，刚刚又成功获取成功了
